# The steps performed here are:


# Loading the data

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from boruta import BorutaPy
import pandas as pd
#import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import joblib

In [5]:
import pandas as pd


df2 = pd.read_csv("/Users/swetarai/BLOOD_SYNOVIUM_COMBINE/GPL570_2_DATA_BLOOD_SYNO/272_776_GPL570_BLOOD_SYNO_exp_pheno.csv", index_col=0)
df2= df2.drop("Gene_Symbol", axis=1)
label_encoder = LabelEncoder()
df2['gender'] = label_encoder.fit_transform(df2['gender'])
df2['sample_type'] = label_encoder.fit_transform(df2['sample_type'])
df2['disease_state'] = label_encoder.fit_transform(df2['disease_state'])

In [6]:
df2

DDR1 /// MIR4640      RFC2     HSPA6      PAX8    GUCA1A  \
0            2.928353  2.681279  3.200373  3.008607  1.814431   
1            2.919860  2.642563  3.187529  2.991917  1.766750   
2            2.862128  2.689835  3.253123  2.971649  1.773704   
3            2.889364  2.705528  3.333800  3.020300  1.750219   
4            2.920884  2.733763  3.266168  2.980154  1.768860   
..                ...       ...       ...       ...       ...   
443          2.418759  2.544346  2.719061  2.710897  1.794041   
444          2.463751  2.590074  2.777088  2.558635  1.749932   
445          2.360704  2.523214  2.366575  2.607487  1.745319   
446          2.385554  2.671206  2.763958  2.549335  1.824347   
447          2.431343  2.564830  2.494746  2.557658  1.748276   

     MIR5193 /// UBA7      THRA    PTPN21      CCL5    CYP2E1  ...  LOC389641  \
0            3.035352  2.794960  1.993711  3.573319  1.875712  ...   2.531248   
1            3.072702  2.880967  2.036722  3.561053  1.895540  ...   2.541923   
2            3.045336  2.872246  1.892788  3.585422  1.928704  ...   2.497606   
3            3.086978  2.900855  2.033047  3.598813  1.828633  ...   2.453638   
4            3.085212  2.806505  1.898818  3.527495  1.766527  ...   2.527991   
..                ...       ...       ...       ...       ...  ...        ...   
443          3.221841  2.933400  2.110611  3.539862  2.292141  ...   2.541818   
444          3.268715  2.886809  1.995671  3.566206  1.978512  ...   2.478416   
445          3.198502  2.913508  2.104843  3.526773  2.160257  ...   2.340760   
446          3.238655  2.987705  1.898630  3.551848  2.045166  ...   2.434111   
447          3.268024  2.981201  2.103751  3.538103  2.351792  ...   2.626630   

        GALR3  MINOS1-NBL1 /// NBL1  MROH7-TTC4 /// TTC4  LIME1 /// ZGPAT  \
0    2.768501              2.902807             2.950347         2.959096   
1    2.725094              2.862354             2.954725         2.957979   
2    2.771164              2.909786             2.966098         3.007961   
3    2.732430              2.861810             2.958894         3.012335   
4    2.750591              2.897746             2.940008         3.028611   
..        ...                   ...                  ...              ...   
443  2.321079              2.297055             3.055863         3.093241   
444  2.244271              2.341876             3.114304         3.067253   
445  2.292508              2.503396             3.042095         3.043156   
446  2.176570              2.242118             2.996378         3.109793   
447  2.280043              2.471449             3.044077         3.183514   

     C1orf50 /// LOC100129924  HNRNPUL2 /// HNRNPUL2-BSCL2  gender  \
0                    2.856775                     2.308445       0   
1                    2.840451                     2.254894       0   
2                    2.897739                     2.310908       0   
3                    2.901581                     2.444284       0   
4                    2.798850                     2.286731       0   
..                        ...                          ...     ...   
443                  2.764181                     3.103394       0   
444                  2.827804                     3.118542       1   
445                  2.872246                     3.054452       0   
446                  2.818023                     3.162893       0   
447                  2.757565                     3.092004       0   

     sample_type  disease_state  
0              0              0  
1              0              0  
2              0              0  
3              0              0  
4              0              0  
..           ...            ...  
443            0              1  
444            0              1  
445            0              1  
446            0              1  
447            0              1  

[448 rows x 21340 columns]

In [7]:
target_name ='disease_state'
y=df2[target_name]
X =df2.drop(target_name,axis=1)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42, shuffle=True)

# LOGISTIC REGRESSION ON ALL FEATURES:

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,roc_auc_score


In [10]:
from sklearn.linear_model import LogisticRegression
lr1=LogisticRegression()
lr1.fit(X_train,y_train)
y_pred = lr1.predict(X_test)
lgr_pred_proba =lr1.predict_proba(X_test)[:,1]

print("Accuracy score", accuracy_score(y_test,y_pred)*100)
print("Confusion matrix:\n", confusion_matrix(y_test,y_pred))
print("Classification Rrport:\n", classification_report(y_test,y_pred,digits=4))
print("ROC AUC Score", roc_auc_score(y_test,lgr_pred_proba))

/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy score 91.11111111111111
Confusion matrix:
 [[27  6]
 [ 2 55]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.9310    0.8182    0.8710        33
           1     0.9016    0.9649    0.9322        57

    accuracy                         0.9111        90
   macro avg     0.9163    0.8915    0.9016        90
weighted avg     0.9124    0.9111    0.9098        90

ROC AUC Score 0.9771398192450824


# Random forest on all features

In [11]:
from sklearn.ensemble import RandomForestClassifier
RFC= RandomForestClassifier()
import datetime
start = datetime.datetime.now() 
RFC.fit(X_train,y_train)

end =datetime.datetime.now()
print("total execution time:", end-start)
y_pred =RFC.predict(X_test)
rfc_pred_proba =RFC.predict_proba(X_test)[:,1]



print("Accuracy score", accuracy_score(y_test,y_pred)*100)
print("Confusion matrix:\n", confusion_matrix(y_test,y_pred))
print("Classification Rrport:\n", classification_report(y_test,y_pred,digits=4))
print("ROC AUC Score", roc_auc_score(y_test,rfc_pred_proba))

total execution time: 0:00:02.091668
Accuracy score 83.33333333333334
Confusion matrix:
 [[26  7]
 [ 8 49]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.7647    0.7879    0.7761        33
           1     0.8750    0.8596    0.8673        57

    accuracy                         0.8333        90
   macro avg     0.8199    0.8238    0.8217        90
weighted avg     0.8346    0.8333    0.8338        90

ROC AUC Score 0.9165337586390218


# KNN on all features

In [12]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()
KNN.fit(X_train,y_train)
y_pred =KNN.predict(X_test)

print("Accuracy score", accuracy_score(y_test,y_pred)*100)
print("Confusion matrix:\n", confusion_matrix(y_test,y_pred))
print("Classification Rrport:\n", classification_report(y_test,y_pred,digits=4))


Accuracy score 72.22222222222221
Confusion matrix:
 [[21 12]
 [13 44]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.6176    0.6364    0.6269        33
           1     0.7857    0.7719    0.7788        57

    accuracy                         0.7222        90
   macro avg     0.7017    0.7041    0.7028        90
weighted avg     0.7241    0.7222    0.7231        90



# Support vector classifier on all features 

In [13]:
from sklearn.svm import SVC
model =SVC(probability= True)
model.fit(X_train,y_train)
predictions =model.predict(X_test)


print("Accuracy score", accuracy_score(y_test,predictions)*100)
print("Confusion matrix:\n", confusion_matrix(y_test,predictions))
print("Classification Rrport:\n", classification_report(y_test,predictions,digits=4))



Accuracy score 73.33333333333333
Confusion matrix:
 [[22 11]
 [13 44]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.6286    0.6667    0.6471        33
           1     0.8000    0.7719    0.7857        57

    accuracy                         0.7333        90
   macro avg     0.7143    0.7193    0.7164        90
weighted avg     0.7371    0.7333    0.7349        90



# feature selection using boruta 

# using BorutaPy

### 1. trained a base classification model with 4 classifiers- Logistic regression, support vector classifier, KNN, random forest
### 2. identify the most relevant features using borutaPy
### 3. created optimum features
### 4. trained the model with optimal features for all the classifier 
### 5. compared the accurcay of classification with optimum features without optimal features.

# 1. training the basic classification model 

In [14]:
from boruta import BorutaPy
feat_selection =BorutaPy(RFC, n_estimators='auto', verbose =2, random_state=42)


In [15]:
type(X)

pandas.core.frame.DataFrame

In [16]:
y

0      0
1      0
2      0
3      0
4      0
      ..
443    1
444    1
445    1
446    1
447    1
Name: disease_state, Length: 448, dtype: int64

In [17]:
#important to note that boruta works with numpy arrays
X=X.to_numpy()
y=y.to_numpy()

In [19]:
feat_selection.fit(X,y)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	21339
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	21339
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	21339
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	21339
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	21339
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	21339
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	21339
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	0
Tentative: 	1130
Rejected: 	20209
Iteration: 	9 / 100
Confirmed: 	117
Tentative: 	1013
Rejected: 	20209
Iteration: 	10 / 100
Confirmed: 	117
Tentative: 	1013
Rejected: 	20209
Iteration: 	11 / 100
Confirmed: 	117
Tentative: 	1013
Rejected: 	20209
Iteration: 	12 / 100
Confirmed: 	143
Tentative: 	687
Rejected: 	20509
Iteration: 	13 / 100
Confirmed: 	143
Tentative: 	687
Rejected: 	20509
Iteration: 	14 / 100
Confirmed: 	143
Tentative: 	687
Rejected: 	20509
Iteration: 	15 / 100
Confirmed: 	143
Tentative: 	687
Re

BorutaPy(estimator=RandomForestClassifier(n_estimators=257,
                                          random_state=RandomState(MT19937) at 0x1192B0440),
         n_estimators='auto', random_state=RandomState(MT19937) at 0x1192B0440,
         verbose=2)

In [20]:
feat_selection.support_

array([False, False, False, ..., False,  True, False])

In [21]:
print('Ranking: ', feat_selection.ranking_ )

Ranking:  [14496   693 16883 ...  9515     1 20948]


In [22]:
print("No. of significant features:", feat_selection.n_features_)

No. of significant features: 195


In [29]:
selected_rf_features =pd.DataFrame({'Feature': list(X_train.columns),
                                    'Ranking': feat_selection.ranking_})

selected_rf_features.sort_values(by='Ranking')

Feature  Ranking
12783                           TTTY15        1
9524                              MED6        1
17175                            WDFY1        1
5947                               B2M        1
11736                           PRRC2C        1
...                                ...      ...
9313                              BRDT    20948
9240                               IL7    20948
9208   GP1BB /// SEPT5 /// SEPT5-GP1BB    20948
9616                CDK3 /// TEN1-CDK3    20948
21338                      sample_type    20948

[21339 rows x 2 columns]

In [30]:
rank_1_features = selected_rf_features[selected_rf_features['Ranking'] == 1]['Feature'].tolist()
rank_1_features

['THRA',
 'JAK1',
 'ND2',
 'ATP6',
 'COX2',
 'PRR14L',
 'ELMOD2',
 'TGOLN2',
 'PPIP5K1',
 'RHOA',
 'TCAIM',
 'DNAJC7',
 'MYCBP2',
 'GSTO1',
 'BCORP1',
 'TRIM69',
 'RNF103',
 'DDX3Y',
 'PRPF8',
 'JTB',
 'ATP6V0E1',
 'HNRNPU',
 'HSP90B1 /// MIR3652',
 'LDHA',
 'RPS27',
 'H2AFZ',
 'RAB11A',
 'STAT1',
 'TRA2B',
 'SEPHS2',
 'SF3B1',
 'SMARCC1',
 'USP9X',
 'ACLY',
 'PUM1',
 'SRRM1',
 'VBP1',
 'SUPT4H1',
 'NFKBIA',
 'ZNHIT1',
 'EIF1B',
 'B2M',
 'RPS4Y1',
 'SLC25A36',
 'SDHC',
 'PTGR2 /// ZNF410',
 'EIF1',
 'BIRC2',
 'UQCR11',
 'BRD4',
 'GGPS1',
 'TCOF1',
 'TBCC',
 'BLOC1S1',
 'TNFSF10',
 'VAMP7',
 'TRAF4',
 'ATP6V1C1',
 'SGSM3',
 'GALNT3',
 'DDB2',
 'PDCD6',
 'EML3',
 'TRAPPC3',
 'S100A9',
 'FAM193A',
 'POLB',
 'COIL',
 'TRIP4',
 'JUND',
 'MRPS14',
 'R3HDM2',
 'FBLN2',
 'LYRM1',
 'NMI',
 'SLC5A6',
 'CD37',
 'ZNF140',
 'ACOT13',
 'VAMP5',
 'PCMT1',
 'ACVR2A',
 'ZNF821',
 'GTF2E1',
 'BATF',
 'CASP1',
 'PRKY',
 'LRRC6',
 'AP3D1',
 'KDM5D',
 'MAP3K7',
 'MED6',
 'GPR171',
 'NCOR2',
 'HUWE1',
 'GLG

In [31]:
# this is how we can make a list of the selected features
selected_feats = X_train.columns[(feat_selection.support_)]

# let's print some stats
print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feats)))

total features: 21339
selected features: 195


In [33]:
selected_feats

Index(['THRA', 'JAK1', 'ND2', 'ATP6', 'COX2', 'PRR14L', 'ELMOD2', 'TGOLN2',
       'PPIP5K1', 'RHOA',
       ...
       'LRRK2', 'LOC100506299', 'TSIX', 'GIMAP2', 'CXorf23', 'LOC101927482',
       'LRR1', 'LOC344887', 'KIAA1841', 'gender'],
      dtype='object', length=195)

In [32]:
pd.Series(selected_feats).to_csv('/Users/swetarai/BLOOD_SYNOVIUM_COMBINE/GPL570_2_DATA_BLOOD_SYNO/selected_features.csv', index=False)

In [25]:
best_features = feat_selection.transform(X)

In [26]:
best_features.shape 

(448, 195)

In [27]:
best_features

array([[2.79496017, 3.16401814, 3.70208426, ..., 2.05496124, 2.54005354,
        0.        ],
       [2.88096721, 3.2143698 , 3.68676152, ..., 2.0889216 , 2.5228551 ,
        0.        ],
       [2.87224646, 3.16657458, 3.70708054, ..., 2.10042529, 2.67158403,
        0.        ],
       ...,
       [2.91350845, 3.3835675 , 3.70080333, ..., 1.82109665, 2.22826758,
        0.        ],
       [2.98770515, 3.39858212, 3.69944368, ..., 1.83126989, 2.57882642,
        0.        ],
       [2.98120124, 3.41199814, 3.67852413, ..., 1.85647806, 2.44200495,
        0.        ]])

In [29]:
best_features.shape, y.shape

((156, 58), (156,))

In [35]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 =train_test_split(best_features,y,test_size=0.1, random_state=42, shuffle= True)



In [36]:
X_train1.shape, y_train1.shape


((403, 195), (403,))

In [37]:
X_test1.shape, y_test1.shape

((45, 195), (45,))

# #training

# logistic regression 

In [38]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train1, y_train1)

y_pred1=lr.predict(X_test1)
lgr_pred_proba1 = lr.predict_proba(X_test1)[:,1]



print("Accuracy score", accuracy_score(y_test1,y_pred1)*100)
print("Confusion matrix:\n", confusion_matrix(y_test1,y_pred1))
print("Classification Rrport:\n", classification_report(y_test1,y_pred1,digits=4))
print("ROC AUC Score", roc_auc_score(y_test1,lgr_pred_proba1))

Accuracy score 93.33333333333333
Confusion matrix:
 [[10  2]
 [ 1 32]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.9091    0.8333    0.8696        12
           1     0.9412    0.9697    0.9552        33

    accuracy                         0.9333        45
   macro avg     0.9251    0.9015    0.9124        45
weighted avg     0.9326    0.9333    0.9324        45

ROC AUC Score 0.9823232323232324


/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# random forest

In [39]:
from sklearn.ensemble import RandomForestClassifier
RFC1= RandomForestClassifier()
RFC1.fit(X_train1,y_train1)

y_pred1 =RFC1.predict(X_test1)




print("Accuracy score", accuracy_score(y_test1,y_pred1)*100)
print("Confusion matrix:\n", confusion_matrix(y_test1,y_pred1))
print("Classification Rrport:\n", classification_report(y_test1,y_pred1,digits=4))


Accuracy score 88.88888888888889
Confusion matrix:
 [[11  1]
 [ 4 29]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.7333    0.9167    0.8148        12
           1     0.9667    0.8788    0.9206        33

    accuracy                         0.8889        45
   macro avg     0.8500    0.8977    0.8677        45
weighted avg     0.9044    0.8889    0.8924        45



# kNN

In [40]:
from sklearn.neighbors import KNeighborsClassifier
KNN1 = KNeighborsClassifier()
KNN1.fit(X_train1,y_train1)
y_pred1 =KNN1.predict(X_test1)

print("Accuracy score", accuracy_score(y_test1,y_pred1)*100)
print("Confusion matrix:\n", confusion_matrix(y_test1,y_pred1))
print("Classification Rrport:\n", classification_report(y_test1,y_pred1,digits=4))

Accuracy score 88.88888888888889
Confusion matrix:
 [[12  0]
 [ 5 28]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.7059    1.0000    0.8276        12
           1     1.0000    0.8485    0.9180        33

    accuracy                         0.8889        45
   macro avg     0.8529    0.9242    0.8728        45
weighted avg     0.9216    0.8889    0.8939        45



# SUPPORT VECTOR MACHINE

In [41]:
from sklearn.svm import SVC
model1 =SVC(probability= True)
model1.fit(X_train1,y_train1)
predictions1 =model1.predict(X_test1)


print("Accuracy score", accuracy_score(y_test1,predictions1)*100)
print("Confusion matrix:\n", confusion_matrix(y_test1,predictions1))
print("Classification Rrport:\n", classification_report(y_test1,predictions1,digits=4))



Accuracy score 84.44444444444444
Confusion matrix:
 [[ 9  3]
 [ 4 29]]
Classification Rrport:
               precision    recall  f1-score   support

           0     0.6923    0.7500    0.7200        12
           1     0.9062    0.8788    0.8923        33

    accuracy                         0.8444        45
   macro avg     0.7993    0.8144    0.8062        45
weighted avg     0.8492    0.8444    0.8464        45

